services:
  lyftr-backend:
    image: cwlumm/lyftr-backend:latest
    container_name: lyftr-backend
    volumes:
      - ./lyftr_data/:/app/data:rw
    networks: 
      - mynet
    environment:
       ENV: production
       PORT: 3008
       JWT_SECRET: ${JWT}
       CORS_ORIGIN: https://lyftr.micedric.dpdns.org:9001
       DB_TYPE: sqlite
       DB_PATH: /app/data/lyftr.db
       REGISTRATION: first-user
    ports:
      - 3008:3008
    restart: unless-stopped
    labels:
      - "sablier.enable=true"
      - "sablier.group=lyftr"

  lyftr-frontend:
    image: cwlumm/lyftr-frontend:latest
    container_name: lyftr-frontend
    depends_on:
      - lyftr-backend
    restart: unless-stopped
    environment:
      - BACKEND_ORIGIN=lyftr-backend:3008  
    networks:
      - mynet
    labels:
      - "traefik.enable=true"

      # Routing / Subdomain
      - "traefik.http.routers.lyftr.rule=Host(`lyftr.micedric.dpdns.org`)"
      - "traefik.http.routers.lyftr.entrypoints=websecure"
      - "traefik.http.routers.lyftr.tls.certresolver=myresolver"
      - "traefik.http.routers.lyftr.middlewares=lyftr-sablier"
      - "traefik.http.services.lyftr.loadbalancer.server.port=80"

      # Sablier: Container darf trotz Stopp im Routing bleiben
      - "traefik.docker.allownonrunning=true"

      # Sablier-Gruppierung
      - "sablier.enable=true"
      - "sablier.group=lyftr"

      # Sablier-Middleware-Konfiguration (alles unter demselben Namen!)
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.group=lyftr"
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.sessionDuration=50m"
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.dynamic.displayName=Lyftr"
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.dynamic.theme=ghost"
      - "traefik.http.middlewares.lyftr-sablier.plugin.sablier.dynamic.refreshFrequency=3s"


networks:
  mynet:
    external: true